"""Entity extraction — simple heuristic (no LLM required)."""

from __future__ import annotations

import re
from typing import List, Set, Tuple

# Common patterns for entity/concept extraction
_ENTITY_PATTERNS = [
    # Projects: "Project Phoenix"
    (r"\b(Project(?:\s+[A-Z][A-Za-z0-9_-]*)+)\b", "project"),
    # Full names: "Alice Smith"
    (r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+)+)\b", "person"),
    # Single proper names: "Alice", "Bob"
    (r"\b([A-Z][a-z]{2,})\b", "person"),
    # Known concept patterns: "X is Y", "X means Y"
    (r"\b([A-Z][a-z]+(?:\s+[a-z]+){0,2})\s+(?:is|are|means?|refers?\s+to)\b", "concept"),
    # Project/product names with quotes or backticks
    (r"[`\"']([A-Za-z][A-Za-z0-9_-]+)[`\"']", "project"),
    # URLs and domains
    (r"\b(?:https?://|www\.)([a-zA-Z0-9.-]+)", "resource"),
    # Hashtag entities
    (r"#([a-zA-Z][a-zA-Z0-9_-]+)", "topic"),
    # Email-like (local@domain)
    (r"\b([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})\b", "contact"),
]

# Stopwords to filter out false-positive entities
STOP_WORDS: Set[str] = {
    # --- Common English stop words (Title-case variants) ---
    "The",
    "This",
    "That",
    "These",
    "Those",
    "There",
    "Then",
    "They",
    "When",
    "Where",
    "What",
    "Which",
    "While",
    "With",
    "From",
    "Into",
    "About",
    "After",
    "Before",
    "Between",
    "Through",
    "During",
    "Without",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
    "First",
    "Second",
    "Third",
    "Last",
    "Next",
    "Each",
    "Every",
    # --- Common English stop words (lowercase) ---
    "the",
    "a",
    "an",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "of",
    "in",
    "on",
    "at",
    "to",
    "for",
    "and",
    "or",
    "but",
    "not",
    "with",
    "by",
    "from",
    "as",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "between",
    "under",
    "over",
    "again",
    "further",
    "then",
    "once",
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "all",
    "each",
    "every",
    "both",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "nor",
    "only",
    "own",
    "same",
    "so",
    "than",
    "too",
    "very",
    "can",
    "will",
    "just",
    "should",
    "now",
    "also",
    "any",
    "its",
    "it",
    "he",
    "she",
    "we",
    "they",
    "you",
    "me",
    "my",
    "your",
    "his",
    "her",
    "our",
    "their",
    "them",
    "what",
    "which",
    "who",
    "whom",
    "this",
    "that",
    "these",
    "those",
    "if",
    "else",
    "about",
    "up",
    "out",
    "off",
    "down",
    # --- Programming keywords / Python builtins ---
    "str",
    "dict",
    "type",
    "int",
    "float",
    "bool",
    "list",
    "set",
    "tuple",
    "None",
    "True",
    "False",
    "class",
    "def",
    "return",
    "import",
    "from",
    "object",
    "bytes",
    "bytearray",
    "frozenset",
    "complex",
    "memoryview",
    "range",
    "enumerate",
    "zip",
    "map",
    "filter",
    "sorted",
    "reversed",
    "iter",
    "next",
    "len",
    "max",
    "min",
    "sum",
    "abs",
    "round",
    "pow",
    "hash",
    "id",
    "isinstance",
    "issubclass",
    "callable",
    "hasattr",
    "getattr",
    "setattr",
    "delattr",
    "property",
    "staticmethod",
    "classmethod",
    "super",
    "self",
    "cls",
    "lambda",
    "yield",
    "async",
    "await",
    "try",
    "except",
    "finally",
    "raise",
    "assert",
    "with",
    "pass",
    "break",
    "continue",
    "global",
    "nonlocal",
    "del",
    "and",
    "or",
    "not",
    "in",
    "is",
    "while",
    "for",
    "True",
    "False",
    "None",
    "Exception",
    "ValueError",
    "TypeError",
    "KeyError",
    "IndexError",
    "AttributeError",
    "RuntimeError",
    "StopIteration",
    "Value",
    "Key",
    "Index",
    "Error",
    # --- HTTP / URL fragments ---
    "http",
    "https",
    "www",
    "com",
    "org",
    "io",
    "net",
    "dev",
    "app",
    "url",
    "uri",
    "api",
    "endpoint",
    # --- API doc noise ---
    "parameter",
    "parameters",
    "returns",
    "raises",
    "example",
    "note",
    "see",
    "also",
    "description",
    "arguments",
    "args",
    "kwargs",
    "param",
    "return",
    "raise",
    "throw",
    "throws",
    "exception",
    "deprecated",
    "version",
    "since",
    "todo",
    "fixme",
    "warning",
    "WARNING",
    "NOTE",
    "TODO",
    "FIXME",
    "XXX",
    "Parameter",
    "Parameters",
    "Returns",
    "Raises",
    "Example",
    "Note",
    "See",
    "Also",
    "Description",
    "Arguments",
    # --- Generic noise words (from API docs / READMEs) ---
    "Best",
    "General",
    "Same",
    "Augmenting",
    "Answers",
    "Any",
    "Discovery",
    "Function",
    "Method",
    "Module",
    "Package",
    "Class",
    "Instance",
    "Variable",
    "Constant",
    "Attribute",
    "Property",
    "Field",
    "Element",
    "Item",
    "Value",
    "Result",
    "Output",
    "Input",
    "Source",
    "Target",
    "Default",
    "Custom",
    "New",
    "Old",
    "Current",
    "Local",
    "Global",
    "Static",
    "Public",
    "Private",
    "Internal",
    "External",
    "Use",
    "Read",
    "Write",
    "Scan",
    "Search",
    "List",
    "Stats",
    "Update",
    "Index",
    "Log",
    "Wiki",
    "Project",
    "Add",
    "Remove",
    "Delete",
    "Create",
    "Get",
    "Set",
    "Name",
    "Type",
    "Data",
    "Info",
    "Config",
    "Option",
    "True",
    "False",
    # --- MCP / server noise ---
    "mcp",
    "servers",
    "server",
    "client",
    "handler",
    "middleware",
    "MCP",
    "Servers",
    "Server",
    "Client",
    # --- Short generic words that are noise ---
    "get",
    "set",
    "put",
    "post",
    "delete",
    "patch",
    "head",
    "run",
    "run",
    "try",
    "let",
    "var",
    "const",
}

# Python builtins for additional filtering
_PYTHON_BUILTINS = frozenset(dir(__builtins__)) if isinstance(__builtins__, dict) else frozenset(dir(__builtins__))

# Backwards-compatible alias
_STOPWORDS = STOP_WORDS


def extract_entities(text: str) -> List[Tuple[str, str]]:
    """Extract entities from text using heuristic patterns.

    Returns:
        List of (entity_name, entity_type) tuples, deduplicated.
    """
    seen: Set[str] = set()
    entities: List[Tuple[str, str]] = []

    for pattern, etype in _ENTITY_PATTERNS:
        for match in re.finditer(pattern, text):
            name = match.group(1).strip()

            # --- Minimum quality rules ---
            # Must be at least 2 characters
            if len(name) < 2:
                continue

            # Must contain at least one letter
            if not re.search(r"[A-Za-zÀ-ÖØ-öø-ÿ]", name):
                continue

            # Reject single-character entities
            if len(name) == 1:
                continue

            key = name.lower()

            # Reject all-lowercase entities shorter than 4 characters
            # (short lowercase words are almost always noise from code/docs)
            if name.islower() and len(name) < 4:
                continue

            # Check stop-words (case-insensitive)
            if key in _STOPWORDS or name in _STOPWORDS:
                continue

            # Reject Python builtin names (case-insensitive)
            if key in _PYTHON_BUILTINS:
                continue

            if key not in seen:
                seen.add(key)
                entities.append((name, etype))

    return entities
